openapi: 3.0.0
info:
  title: async serverless application shop API
  description: |-
    async serverless application shop API
  version: 1.0.0
servers:
  - url: 'http://localhost:{port}/shop/'
    description: dev
    variables:
      port:
        default: '8080'
  - url: 'https://api.<domain-name>/shop/'
    description: stg

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  # /healthcheck: # api-gatewayでエンドポイントを/v1/を指定しているため
  /v1/healthcheck:
    get:
      tags:
        - healthcheck
      summary: ヘルスチェックAPI
      description: APIが正常に動作しているかを確認します。
      operationId: healthcheck
      responses:
        '200':
          description: API is up and running
          content:
            application/json:
              schema:
                $ref: './api/responses/HealthCheck.yaml'
      security: []  # healthcheckでは認証を必要としないため

  # ユーザ系API
  /v1/users:
    $ref: './api/v1/users/paths/User.yaml'
  /v1/users/me:
    $ref: './api/v1/users/paths/Me.yaml'
  /v1/users/profiles:
    $ref: './api/v1/users/paths/Profile.yaml'
  /v1/users/profiles/me:
    $ref: './api/v1/users/paths/ProfileMe.yaml'

  # 商品系API
  /v1/products:
    $ref: './api/v1/products/paths/Products.yaml'
  /v1/products/{productID}:
    $ref: './api/v1/products/paths/ProductByID.yaml'

  # 外部決済サービス向け顧客情報系API
  /v1/payment/customers/{userID}:
    $ref: './api/v1/payments/paths/CustomerByUserID.yaml'
  /v1/payment/customers:
    $ref: './api/v1/payments/paths/Customers.yaml'

  # クレジットカード系API
  /v1/payments/cards:
    $ref: './api/v1/payments/paths/CreditCard.yaml'

  # 予約系API
  /v1/payments/reservations:
    $ref: './api/v1/payments/paths/Reservation.yaml'

  # 注文系API
  /v1/payments/charges:
    $ref: './api/v1/payments/paths/Charge.yaml'
  /v1/payments/charges/histories:
    $ref: './api/v1/payments/paths/ChargeHistories.yaml'
