services:
  shop-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.7
    container_name: shop-api
    working_dir: /go/src/github.com/tamaco489/sns_sqs_lambda_fanout_architecture/api/shop
    volumes:
      - ./shop:/go/src/github.com/tamaco489/sns_sqs_lambda_fanout_architecture/api/shop
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8080:8080"
    env_file:
      - ./shop/.env
